### ISSUE TITLE
Implement social login

### ISSUE THREAD

**Issue by bobman38** [montessori-ressources/web#2]
Need to choose the right social systems:
* Facebook ?
* Google ?

**Comment by StaudenmannM** [comment]
Actually the signup process should allow several system (Facebook, or Google or Twitter, or host in the app, etc..). is it an issue with the current bundle ?

**Comment by bobman38** [comment]
hello

Just searching for the right one, this seems pretty common : https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/index.md

It integrate with FOSUserBundle,

**Comment by bobman38** [comment]
fixed by #18

**Comment by bobman38** [comment]
#18 is now merged !
