### ISSUE TITLE
Better nomenclature massive upload screen

### ISSUE THREAD

**Issue by bobman38** [montessori-ressources/web#27]
- See work of @StaudenmannM on plain HTML/CSS/JS
- image upload area for multiple images
- manage the collection !

**Comment by bobman38** [comment]
@StaudenmannM do you have shared with me your work on uploading ? I don't remember... if you can drop a zip or a link thanks !

**Comment by StaudenmannM** [comment]
I think I discovered how to integrate it in Symfony (that why I made a 1st PR :)).Give me few days to test it.

**Comment by bobman38** [comment]
From the Trello the page must contains
* label
* description
* description with hole
* nomenclature mode (simple or scientific)
* illustration type (aquqrel picture drawing clipart)
* image set

**Comment by bobman38** [comment]
@StaudenmannM maybe you can give this task to @analuspi ?

**Comment by StaudenmannM** [comment]
Hi
Yes good idea. @analuspi feelf ree to reuse branch content or start from scratch :)

**Comment by bobman38** [comment]
Let's say this one is fixed because #71 is allowing multi file upload,
