### ISSUE TITLE
Heroku not working with in-house asset creation

### ISSUE THREAD

**Issue by bobman38** [montessori-ressources/web#4]
The Heroku app is linked to the `develop` branch to show project avancement.

But Heroku doesn't keep data stored inside the app path. So currently images are deleted each time the Heroku app is shut down / started (it is part of the 12 factor app to not store assets at app location.)

Do we want to implement something like S3 for assets ?

**Comment by bobman38** [comment]
This can be the solution easy to implement https://github.com/1up-lab/OneupFlysystemBundle

**Comment by bobman38** [comment]
See #15

**Comment by StaudenmannM** [comment]
Fixed with the PR.Closing
