### ISSUE TITLE
Handle search input on cards

### ISSUE THREAD

**Issue by bobman38** [montessori-ressources/web#40]
Must show cards that correspond to searched terms.

No need to press enter to show items, each new letter will narrow the research after the 3 first letters.

**Comment by bobman38** [comment]
Hello,

@StaudenmannM need your advice...

Currently I show all nomenclature, and when user is searching then it remove all and filter:

![2019-06-13 09 49 03](https://user-images.githubusercontent.com/4988590/59438035-b3208180-8dc0-11e9-8f24-e06720af69ca.gif)

Is it an expected behaviour ? Do you see it different ?

**Comment by StaudenmannM** [comment]
Hi Julien,
Based on the [the wiki](https://github.com/montessori-ressources/core/wiki/1.1.-Nomenclatures), the initial volume of data will be 100 nomenclatures at the begining and 500 at the end of the year.
I suggest to keep the filter feature for the "personal" list page, used by each user to manage its own list of nomenclatures but add a real search engine for this page that list all nomenclatures from all users. 
We should even use a pagination to avoid performance impacts and only load x nomenclature per page (x is a flexible value between 10 and 50).
I don't know any search engine in PHP so we could start with custom code and SQL queries, except if you know a PHP search engine tool.
Does it make sense ?

**Comment by bobman38** [comment]
So if I resume: 

- no search feature on nomenclature index page ?
- a search / filter for a personal nomenclature page ? (see only own nomenclature)
- pager system on index + personal page ?

Currently there is no search engine, juste a `name LIKE '%searchterm%'` so it's very primitive yeah :) If we want to implement some kind of content indexing we must use a tool like Lucene/Solr Elasticsearch... A different story maybe for v2 !

https://packagist.org/?query=search&type=symfony-bundle

**Comment by StaudenmannM** [comment]
Not sure I follow you but here is my resume:

- Nomenclature index page: Search based on SQL queries (LIKE '%serchterm%) + pagination to limit the number of loaded results.
- Filter (same as your demo above) on personal nomenclature page (to be created)
- I don't understand what you mean by "pager system on index + personal page ?"

I agree with your comment on search. Will be V but we need a php search, except if we can host other techologies on the current provider.
Luce

**Comment by bobman38** [comment]
FIxed by #44
