### ISSUE TITLE
Add help pages for user

### ISSUE THREAD

**Issue by bobman38** [montessori-ressources/web#65]
We must add some information to help the user regarding activities on the application:
- how to add a new nomenclature
- how to edit a nomenclature

Maybe we can use external service for that ? readthedocs or gitdocs for example.

**Comment by bobman38** [comment]
@analuspi good one

**Comment by bobman38** [comment]
Better to put the documentation inside the application. For example in the upload screen add a text to explain how to to upload files

![image](https://user-images.githubusercontent.com/4988590/67307481-96126280-f4c6-11e9-8508-1a1844ac6250.png)

**Comment by StaudenmannM** [comment]
Tooltips on fields and fake/simple introduction added in PR #87. Will need help to finalize the texts.
